### ISSUE TITLE
Correct Typos in study.md

### ISSUE THREAD

**Issue by bernardlee** [ga-wdi-boston/rails-api-study#119]
"Responsiblities" should be "Responsibilities".

**Comment by jrhorn424** [comment]
@tvlangley @payne-chris-r Any idea what happened here? Was @bernardlee's PR ignored or was it used as a basis for the update in 8ab7311?

**Comment by MicFin** [comment]
Looks like it was used in the commit
https://github.com/ga-wdi-boston/rails-api-study/commit/8ab73114fd91220c7b3037216ab386edaf2c0221#diff-2fc0e52245764239acae01b60cc3dc7cL38

**Comment by jrhorn424** [comment]
@MicFin I'm specifically asking whether effort was duplicated.

What I really care about is: Do people know that they should look at open PRs when prepping as part of the process?

**Comment by payne-chris-r** [comment]
Yes, people (talking only about myself) know it. Though sometimes the "duplicating" work takes less time than reviewing an old branch that may or may not be up-to-date anyway. If it resolves issues it's one thing, if it's just a template update and I have to do it anyway for the current iteration, why bother reviewing the stale branch when I'm going to have to do it again anyway? To me that feels more like duplicating work than just doing it from a template that I know is up to date?

**Comment by tvcrawley** [comment]
I used the existing PR as a basis for my PR.
